# .circleci/config.yml
version: 2.1

jobs:
  build:
    docker:
      - image: node:14.17 # Choose the Node.js version you prefer

    working_directory: ~/app

    steps:
      - checkout

      # Install dependencies
      - run: npm install

      # Run tests
      - run: npm test

# Specify workflows
workflows:
  version: 2
  build:
    jobs:
      - build
